### ISSUE TITLE
Error with LuckPerms V5

### ISSUE THREAD

**Issue by austin4195** [allenclan23/MSEssentials#7]
**Describe the bug**
A clear description of the bug: An error seems to be thrown mentioning the API for LuckPerms whenever booting with LuckPerms V5 and MSEssentials

**To Reproduce**
Steps to reproduce the behavior: Attempt to start Velocity proxy with LuckPerms V5 + MSEssentials

**Expected behavior**
Proxy should startup successfully.

**Screenshots**

**Desktop (please complete the following information):**
 - Velocity Version: 1.1.0
 - MSEssentials Version: 1.0.
 - Additional Plugins installed on velocity: 
AdvancedBan
CraftingStore
LuckPerms
MaintenanceVelocity
MSServer
Plan
ServerListPlus

**Additional context**
Proxy boots fine with MSEssentials disabled.

**Comment by allenclan23** [comment]
Can you post the error that is thrown in console?

**Comment by allenclan23** [comment]
I have began looking into updating for version 5. It will take some time till it is complete.

**Comment by austin4195** [comment]
As a temporary solution, would it be possible to make MSEssentials wait until LuckPerms fully loads? LuckPerms has their legacy API extension but it doesnt load that until later in startup

**Comment by allenclan23** [comment]
@austin4195 MSEssentials relies on version 4.4 of luckperm's api, you can try using the bridge : [Located Here](https://ci.lucko.me/job/extension-legacy-api/lastSuccessfulBuild/artifact/build/libs/extension-legacy-api-1.0.0.jar)

**Comment by austin4195** [comment]
Tried that, and it cant load before MSEssentials calls for it

**Comment by allenclan23** [comment]
Okay, I'll let you know when I've completed the update.
